chore: add png-luau
Unfortunately, using pesde does not seem like an option. png-luau uses
script requires, which only work in a Roblox context, but I really want
the generation script to work on the filesystem, and switching to string
requires is not much work. pesde has a patching feature, but I kept
getting:

error: package not found in graph

This is probably an error on my side, but I have spent so much time
fiddling with pesde at this point that I would rather just manually add
the package.